# Site settings
title:          Kyla del Rosario
description:    "Technical Writer/UX Designer"
url:            "http://krosa.github.io"

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Kyla del Rosario
  url:          https://kyladelrosario.com
  email:        kyla.r.delrosario@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
